apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arlo-mqtt.fullname" . }}
  labels:
    {{- include "arlo-mqtt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arlo-mqtt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arlo-mqtt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arlo-mqtt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - "-d"
            - "--broker"
            - {{ required ".Values.mqtt.broker is required!" .Values.mqtt.broker | quote }}
            {{- with .Values.mqtt.port }}
            - "--port"
            - {{ . | quote }}
            {{- end }}
          env:
            - name: ARLO_USER
              {{- toYaml (required ".Values.credentials.arlo.username is required!" .Values.credentials.arlo.username) | nindent 14 }}
            - name: ARLO_PASS
              {{- toYaml (required ".Values.credentials.arlo.password is required!" .Values.credentials.arlo.password) | nindent 14 }}
            - name: ARLO_MQTT_USER
              {{- toYaml (required ".Values.credentials.mqtt.username is required!" .Values.credentials.mqtt.username) | nindent 14 }}
            - name: ARLO_MQTT_PASS
              {{- toYaml (required ".Values.credentials.mqtt.password is required!" .Values.credentials.mqtt.password) | nindent 14 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
