apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "traefik-forward-auth.fullname" . }}
  labels:
    {{- include "traefik-forward-auth.labels" . | nindent 4 }}

spec:
  forwardAuth:
    address: http://{{ include "traefik-forward-auth.fullname" . }}:{{ .Values.service.port }}
    authResponseHeaders:
      - X-Forwarded-User
