{{- if not .Values.credentials.arlo.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arlo-mqtt.arloSecretName" . }}
  labels:
    {{- include "arlo-mqtt.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.credentials.arlo.username | b64enc }}
  password: {{ .Values.credentials.arlo.password | b64enc }}
{{- end }}
