# Default values for arlo-mqtt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mqtt:
  broker: mosquitto
  port: 1883

credentials:
  arlo:
    # If existingSecret is specified, it'll be used directly, ignoring all other values.
    # The secret must contain keys username and password.
    # existingSecret: ""

    # These plaintext values are used to create a secret if existingSecret is not specified.
    username: me@example.com
    password: supersecret

    # Extra options to pass to Pyaarlo. Encoded as "extras_json" in the secret.
    # See here for details: https://github.com/twrecked/pyaarlo
    # extras:
    #   tfa_source: imap
    #   tfa_type: email
    #   tfa_host: imap.host.com
    #   tfa_username: your-user-name
    #   tfa_password: your-imap-password
    extras: {}

  mqtt:
    # If existingSecret is specified, it'll be used directly, ignoring username and password.
    # The secret must contain keys username and password.
    # existingSecret: ""

    # These plaintext values are used to create a secret if existingSecret is not specified.
    username: me
    password: supersecret

replicaCount: 1

image:
  repository: jasonxh/arlo-mqtt
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
